### ISSUE TITLE
Unable to extend themes

### ISSUE THREAD

**Issue by berthob98** [Opencast-Moodle/moodle-local_och5p#1]
I currently get the error "Unable to extend themes" on Moodle Version: 3.6.4
Got the Plugin working fine on another Server with Moodle Version: 3.6.7+
![Screenshot from 2021-04-30 13-45-18](https://user-images.githubusercontent.com/65233148/116691905-cd1adb80-a9bb-11eb-9e2f-d40d93cc7088.png)

**Comment by ferishili** [comment]
I could not find the exact Moodle versions that you used, but I tested on 3.6.10 and 3.5.17+.
Apparently there is no such issue, however this issue most probably comes from the file writing permission, in which you need to check if the apache user (server user) is able to write to those files inside the theme/ directory of your moodle installation.
Make sure those files are writable! Let me know your feedback.

**Comment by berthob98** [comment]
Thank you for your help. The write permission was the problem. Giving the apache group write permission on the theme directory fixed it.

**Comment by berthob98** [comment]
I am now able to select a Video in H5P in the first drop down menu but the second drop down menu in H5P where you should be able to select the type of video (e.g. Presenter (.mp4)) doesn't come up
![Screenshot from 2021-05-05 17-03-11](https://user-images.githubusercontent.com/65233148/117163332-d80eab00-adc3-11eb-9191-31395f6faeb4.png)

**Comment by ferishili** [comment]
Hi @berthob98,
In case of any known issue by retrieving the episode flavor, an Error message should have been displayed. Please try it out and look for any console log error or any type of log related!
It would be nice if you could reinstall the plugin in that particular version  (with new write permission), and then try it out fresh.

**Comment by berthob98** [comment]
There is a 403 forbidden when trying to:
`GET https://moodle-dev8.....de/local/och5p/ajax.php?contextId=25&token=3d2114de4a654&action=videoQualities&identifier=e17e8a5b-7295-436c-8a02-bee9a7e29da6&courseid=2`

I reinstalled the plugin on two diffrent machines both still have the same problem

**Comment by ferishili** [comment]
Alright, that error comes from the part that plugin wants to communicate to the Opencast server via API url API username and API password set in tool_opencast plugin, and it tries to reach this endpoint "/search/episode.json?id={identifier}" 
Make sure you have configured the tool_opencast plugin correctly and that "/search/episode.json" endpoint is accessible!

**Comment by berthob98** [comment]
Thank you for your help.
The API user is correctly configured I tested the user with curl and I am able to use the block to upload videos. The endpoint must not be available.
Under Opnecast 9.0 in /rest_docs.html the /search endpoint is listed but on my servers running Opencast 8.3 the endpoint is not listed.
Could it be that the endpoint was added later?

**Comment by ferishili** [comment]
No Problem.
The search endpoint is in every opencast version! Please try to reach that endpoint with a valid identifier (e.g. using Postman) and let me know the result.

**Comment by berthob98** [comment]
I found the problem we have a cluster setup with seperated admin-, engage-, and worker-nodes and on diffrent nodes are diffrent endpoints available. The /search/episode.json endpoint is only available on the engage node. However the block_opencast and also the och5p plugin requiere endpoints from the admin node aswell.
To me it seems like there is no easy fix for this.

**Comment by ferishili** [comment]
Alright, now we know the case! regarding to that I can add a new config to get/consume external node, but there should be credentials as well. Do you think that could solve your problem?

**Comment by berthob98** [comment]
I am logged in as ROLE_ADMIN, in the documentation it says "Users owning the role ROLE_ADMIN have full access to the External API.". I think credentials can't solve the problem. Maybe I can build a workaround with apache server redirecting /search/episode.json to the engage server

**Comment by ferishili** [comment]
Alright, in this case, I would say, it is better to close this issue, because it is not related to the plugin anymore!
