### ISSUE TITLE
/search/episode.json sent to admin server

### ISSUE THREAD

**Issue by Rillke** [Opencast-Moodle/moodle-local_och5p#2]
Hi, after selecting the opencast video in the H5P, I see a failing AJAX request to Moodle (403) and in our Opencast Admin server a failing request to /search/episode.json (404).

This is because the Admin server does not house the Solr search index, and the Presentation server does not house the API, but the API URL is used [here](https://github.com/Opencast-Moodle/moodle-local_och5p/blob/master/ajax.php#L104) to query the /search/episode.json ?

The [Opencast filter plugin](https://github.com/Opencast-Moodle/moodle-filter_opencast) allows us to specify an engage URI, maybe that one should be used instead?

**Comment by Rillke** [comment]
Note that as an interim solution, we have added to our admin node

```nginx
location /search/ {
    proxy_pass https://presentation.opencast.example.com;
    # the following would be nicer but does not work - credentials are not re-submitted
    #return 307 https://presentation.opencast.example.com$request_uri;
}
```

**Comment by berthob98** [comment]
I have had the same Problem. An option to configure the presentation node for the /search/episode.json request would be really useful.
My workaround was hard coding the correct url just for this request. But it also involves modifying the tool_opencast since the api object comes from the tool_opencast plugin.

**Comment by ferishili** [comment]
Hi @Rillke
that would be nice if you could check if this issue still exists. I did fix it in the latest version of this plugin
Thanks in advance

**Comment by ferishili** [comment]
Closing this issue in favor a the fix in https://github.com/Opencast-Moodle/moodle-local_och5p/commit/c0e0d7e5f59939d1c28e7eacb635b30be45f5554
