### ISSUE TITLE
Clashes with "securing static files"

### ISSUE THREAD

**Issue by Rillke** [Opencast-Moodle/moodle-local_och5p#3]
We have enabled [Securing Static Files](https://docs.opencast.org/r/9.x/admin/#configuration/serving-static-files/#securing-static-files). This causes a 403 forbidden after selecting the episode and the flavor.

![image](https://user-images.githubusercontent.com/2311611/121317934-0d4e7180-c90b-11eb-80ef-5fcf57cddc6e.png)

<h2>HTTP ERROR 403 Forbidden</h2>
<table>
<tr><th>URI:</th><td>/static/mh_default_org/engage-player/7238b6c9-3465-40f0-8d1f-b3234a16ad45/7941dea2-4c8c-419d-b3a3-7048841cffb7/presenter_0ea51681_eb64_42f7_b868_6a789f66eae2.mp4</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>Forbidden</td></tr>
<tr><th>SERVLET:</th><td>org.ops4j.pax.web.service.spi.model.ServletModel-8</td></tr>
</table>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.28.v20200408</a><hr/>

The plugin should probably perform an LTI login of the user prior to let the user load the videos from presentation.

**Comment by ferishili** [comment]
Hi @Rillke 
that would be nice if you could check if this issue still exists. I did fix it in the latest version of this plugin
Thanks in advance

**Comment by ferishili** [comment]
Closing this issue in favor a the fix in https://github.com/Opencast-Moodle/moodle-local_och5p/commit/c0e0d7e5f59939d1c28e7eacb635b30be45f5554
