### ISSUE TITLE
Cannot insert Opencast video: Illegal string offset 'mimetype'

### ISSUE THREAD

**Issue by fishfree** [Opencast-Moodle/moodle-local_och5p#4]
![image](https://user-images.githubusercontent.com/1741341/133704185-9351ace9-1ad0-46ac-9fe4-2a6d70721030.png)
![image](https://user-images.githubusercontent.com/1741341/133704214-1b30b62a-1db1-46d5-8438-a78841185967.png)

`2021/09/17 08:04:43 [error] 1141#1141: *2603501 FastCGI sent in stderr: "PHP message: PHP Warning:  Illegal string offset 'mimetype' in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Warning:  Illegal string offset 'mimetype' in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Warning:  Illegal string offset 'mimetype' in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Warning:  Illegal string offset 'mimetype' in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Notice:  Undefined index: mimetype in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Warning:  Illegal string offset 'mimetype' in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Notice:  Trying to access array offset on value of type int in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Notice:  Undefined index: mimetype in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Notice:  Trying to access array offset on value of type int in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Notice:  Undefined index: mimetype in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Notice:  Undefined index: mimetype in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Notice:  Trying to access array offset on value of type bool in /home/www/moodle/moodle/local/och5p/ajax.php on line 119PHP message: PHP Notice:  Trying to access array offset on value of type bool in /home/www/moodle/moodle/local/och5p/ajax.php on line 119" while reading response header from upstream, client: 10.2.8.19, server: elearning.***.***, request: "GET /local/och5p/ajax.php?contextId=67778&token=f94187cc6064a&action=videoQualities&identifier=a3e55fde-eb91-4b03-973e-57735a7e24c6&courseid=295 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:"`

Moodle: 3.10
Opencast: 10.2
The integration of Opencast & Moodle has been made successfully with tool_opencast and LTI.

**Comment by fishfree** [comment]
I find that it is caused by videos which only have one track. If we select a video with presenter/presentation 2 tracks. It will work. So, I think we'd better support only 1 track scenario.

**Comment by claudiaballerstedt** [comment]
Hi, What's the status of development? Why is it even possible to select two videos? H5P only handles one.

**Comment by ferishili** [comment]
Hi, unfortunately, the development is not yet insight! And would be something for 2Q. 2023, unless an active contract for this plugin is made!
However, one could only select 1 video, based on the quality and the flavor.

**Comment by ferishili** [comment]
Hi @fishfree,
I guess this issue is fixed in https://github.com/Opencast-Moodle/moodle-local_och5p/commit/c0e0d7e5f59939d1c28e7eacb635b30be45f5554
That would be nice if you could confirm that as well so I can close this issue and continue with others
Thanks in advance

**Comment by ferishili** [comment]
Closing this issue in favor a the fix in https://github.com/Opencast-Moodle/moodle-local_och5p/commit/c0e0d7e5f59939d1c28e7eacb635b30be45f5554
