### ISSUE TITLE
Plugin not available in all content types

### ISSUE THREAD

**Issue by claudiaballerstedt** [Opencast-Moodle/moodle-local_och5p#5]
The plugin is not available in all video upload dialogs within the H5P-Content types

    interactive Video -> Yes

    interactive Book -> No

    course Presentation -> Yes

    Column → No

**Comment by ferishili** [comment]
Hi @claudiaballerstedt,
About this issue, for those two H5P contents that you mentioned in which the opencast upload dialog is not available, I would say: there you need to select the "Interactive Video" as content in the dropdown menu, after that, you will have that upload dialog. Please see the attachment, it applies for the Column content, the interactive Book content is the same.
<img width="646" alt="Screenshot 2023-03-09 at 15 17 10" src="https://user-images.githubusercontent.com/53179227/224052886-acd9e40b-ccdf-48c9-b803-a6ecf653ba8b.png">

**Comment by claudiaballerstedt** [comment]
Hi @ferishili,

Thank you for your reply. We recently installed new updates and now it works. :-)

Best regards, Claudia
