### ISSUE TITLE
Usability improvement of the video selection

### ISSUE THREAD

**Issue by claudiaballerstedt** [Opencast-Moodle/moodle-local_och5p#6]
The video selection fields have no description text. It can be difficult for the user to understand what to choose.
The title of the video is selected in the first field. In the second field, the channel of the video is selected (presentation or presentation). Because it may happen that there are two video files in Opencast.
![Screenshot](https://user-images.githubusercontent.com/121228933/227517984-c9f01c5c-045e-4f53-8833-eaf4df8917de.png)

New field labels:
1) Wählen Sie den Dateinamen des Videos aus. / Select the video file name.
2) Wählen Sie den gewünschten Kanal des Videos aus (Presenter.mp4 oder presentation.mp4) / Select the channel of the video(Presenter.mp4 or presentation.mp4)

Feature Request Hochschule Hannover

**Comment by ferishili** [comment]
This issue is fixed in https://github.com/Opencast-Moodle/moodle-local_och5p/commit/33e06aaa49416ae52faaa76ff0bf53273da47b54
