### ISSUE TITLE
Support for Moodle 4.0 /4.1 and newest Opencast Plugin Releases

### ISSUE THREAD

**Issue by fsufrre** [Opencast-Moodle/moodle-local_och5p#7]
Hello Farbod, 

after installing all the the new releases for moodle/opencast there occured several problems.
First the plugin calles the "apiurl" but "ocinstanceid" should be uses instead.
After hardcoding that there were other errors 404. 
Similar to #2 

We use OC 12.4, Moodle 3.11 and all lates releases.

A fix would be nice.

Thanks!
Frank

**Comment by ferishili** [comment]
THis issue is fixed in https://github.com/Opencast-Moodle/moodle-local_och5p/commit/dfdf95ddcd62ccc282a25932f17415841175e425
