### ISSUE TITLE
renderes.php in theme_boost_union

### ISSUE THREAD

**Issue by elke-hsh** [Opencast-Moodle/moodle-local_och5p#8]
We create a [pull request](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/354) for moodle-theme_boost_union.
Since version v4.1-r2 there exists already a renderers.php to customize css for core_h5p and mod_hvp.

We have multiple servers for moodle, so the way of patching renderes.php by the plugin gui is not an ideal solution.

**Comment by ferishili** [comment]
Please follow this one for core version as well: https://github.com/elan-ev/moodle-local_och5pcore/issues/4

**Comment by ferishili** [comment]
Closed as completed via https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/359
